using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using PortalRestService.Core.ConstantResponse;
using PortalRestService.Core.Models;
using PortalRestService.Core.Repositories;
using PortalRestService.Core.Responses;
using PortalRestService.Infrastructure.Helper;
using PortalRestService.Infrastructure.Repositories.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;

namespace PortalRestService.Infrastructure.Repositories
{
    public class LocationsDispenserRepository : OcppRepository<LocationsDispenserpResponce>, ILocationsDispenserRepository
    {
        private readonly IConfiguration _configuration;
        private readonly string OccpIp = String.Empty;
        private readonly ILocationRepository _locationRepository;
        public LocationsDispenserRepository(Infrastructure.DBContext.ocpp_dbContext dbContext, IConfiguration configuration,
            ILocationRepository locationRepository) : base(dbContext)
        {
            this._configuration = configuration;
            OccpIp = this._configuration.GetSection("OccpIp").GetSection("ip").Value;
            _locationRepository = locationRepository;
        }

        public async Task<LocationsDispenserpResponce> GetLocationsDispenserformap(LocationOpratorRequest request)
        {
            LocationsDispenserpResponce query = new LocationsDispenserpResponce();
            DispenserByLocationIdResponse? dispenserByLocationIdResponse = new DispenserByLocationIdResponse();

            try
            {
                List<long> locationIdlist = await _locationRepository.GetAllLocationIdByObjectId();

                query.data = await (from Charger in request.ChargeBoxId.Any() ? _dbContext.Charger.Where(o => request.ChargeBoxId.Contains(o.ChargeBoxId) && o.IsActive)
                              : _dbContext.Charger.Where(o => o.IsActive)
                              join location in request.LocationIds.Any() ? _dbContext.Locations.Where(x => request.LocationIds.Contains((int)(x.Id)) && locationIdlist.Contains(x.Id)) : _dbContext.Locations.Where(x => locationIdlist.Contains(x.Id)) on Charger.LocationId equals location.Id
                              join address in _dbContext.LocationAddress on location.LocationAddressId equals address.Id
                              join Status in _dbContext.LocationStatus on location.LocationStatusId equals Status.Id
                              select new LocationsDispenser
                              {
                                  CityName = location.LocationAddress.CityName,
                                  CountryName = location.LocationAddress.CountryName,
                                  StateName = location.LocationAddress.StateName,
                                  locationId = location.Id,
                                  Latitude = Charger.Latitude.ToString()!,
                                  Longitude = Charger.Longitude.ToString()!,
                                  LocLatitude = location.LocationAddress.Latitude.ToString(),
                                  LocLongitude = location.LocationAddress.Longitude.ToString(),
                                  LocationName = location.LocationName,
                                  DispenserId = Charger.Id,
                                  ChargeBoxid = Charger.ChargeBoxId,
                                  status = Charger.ChargerStatuses == null || Charger.ChargerStatuses.Count == 0 ? "Offline" :
                                Charger.ChargerStatuses.ToList()[0].Chargerstatus.Replace("charging", "Busy").Replace("Charging", "Busy").Replace("suspendedev", "Busy").Replace("SuspendedEV", "Busy").Replace("suspendedevse", "Busy").Replace("SuspendedEVSE", "Busy")
                              .Replace("finishing", "Busy").Replace("Finishing", "Busy").Replace("preparing", "Busy").Replace("Preparing", "Busy"),
                                  AssetId = Charger.AssetId,
                                  MakeName = Charger.MakeName,
                                  ModelName = Charger.ModelName,
                              }).ToListAsync();

                var groupByLocation = query.data.GroupBy(x => x.LocationName);

                var rand = Random.Shared;
                foreach (var group in groupByLocation)
                {
                    foreach (var charger in group)
                    {
                        charger.IsAutoGenerated = false;
                        if (charger.Latitude == null && charger.Longitude == null)
                        {
                            double baseLat = Convert.ToDouble(charger.LocLatitude);
                            double baseLon = Convert.ToDouble(charger.LocLongitude);
                            double radius = 0.0006;
                            double angle = rand.NextDouble() * Math.PI * 2;
                            double distance = radius * Math.Sqrt(rand.NextDouble());
                            double offsetLat = distance * Math.Cos(angle);
                            double offsetLon = distance * Math.Sin(angle);
                            charger.Latitude = (baseLat + offsetLat).ToString();
                            charger.Longitude = (baseLon + offsetLon).ToString();
                            charger.IsAutoGenerated = true;
                        }
                    }
                }

                if (query.data.Count > 0)
                    query.StatusMessage = RespnoseMessage.Record_found;
                else
                    query.StatusMessage = RespnoseMessage.Record_not_found;
                query.StatusCode = 200;

            }
            catch (Exception ex)
            {
                query.StatusMessage = RespnoseMessage.Opeartion_Failed;
                query.StatusCode = RespnoseCode.Bad_Request;
                query.data = new List<LocationsDispenser>();
            }
            return query;
        }
    }
}
